# Regexps for filtering the artifacts to list in the admin dashboards
# (whole filename has to match)
includeArtifacts: ".*([wx]cdf|prpt|xjpivot|saiku|pdf|xlsx?)"
excludeArtifacts: ".*(plugin[-]samples|bi[-]developers|_tmp).*"
