# NOTE: in addition to this file, you should add the username and password
# of the administrator user to your ~/.kettle/kettle.properties file,
# which should be only readable by the user running Pentaho.
#
# For a stock Pentaho CE install, use this lines and uncomment them:
#
# ARTIFACTCATALOG_RESTAPI_USER=Admin
# ARTIFACTCATALOG_RESTAPI_PWD=password

# Location of the Pentaho REST API 
scheme: "http"
host: "localhost"
port: 8080
baseURI: "/pentaho/api"
